### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by hakimio** [choffmeister/yarn-workspace-isolator#3]
When trying to run on Windows I get error saying: `Error: spawn yarn ENOENT`.

Following seems to be related to the error:
https://github.com/fusionjs/fusion-scaffolder/pull/47
https://stackoverflow.com/questions/37459717/error-spawn-enoent-on-windows

**Comment by choffmeister** [comment]
@hakimio I don't use windows so I cannot really test this. If you provide a PR to fix this I would be willing to merge it. Note though, that the main intention of this tool is to be run inside a multi-stage docker build to produce a small docker image containing only one workspace (and inside the docker image there would be linux around).

**Comment by hakimio** [comment]
@choffmeister sorry, but I am no longer interested in this project and don't have any incentive to contribute a PR.
Anyway, I have provided relevant information to fix this issue in my first post and you can just use Azure windows virtual machine for free to test the changes.

**Comment by choffmeister** [comment]
Won‘t do
